name: Deploy to GitHub Pages

on:
  # Se déclenche à chaque push sur la branche 'main'
  push:
    branches: [ "main" ]
  # Permet de lancer manuellement ce workflow depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions nécessaires pour que l'action puisse écrire sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cette action est spécialisée pour les projets Vite !
      # Elle installe les dépendances, build le projet et le déploie.
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
